/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.laptrinhmang.videocall;

import HubHandler.DisconnectMessage;
import HubHandler.User;
import HubHandler.UserListUpdater;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author unkno
 */
public class Lobby extends javax.swing.JFrame {
    
    private Socket clientSocket;
    private UserListUpdater userListUpdater;

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        
        initComponents();
        this.setTitle("Lobby");
        BThoat.setVisible(false);
        
    }
    
    public void setClientSocket(Socket clientSocket) {
        this.clientSocket = clientSocket;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JTextField();
        BGiaNhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListUser = new javax.swing.JList<>();
        CBUser = new javax.swing.JComboBox<>();
        BGoi = new javax.swing.JButton();
        BThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên tài khoản");

        BGiaNhap.setText("Gia nhập");
        BGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGiaNhapActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListUser);

        BGoi.setText("Gọi");
        BGoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGoiActionPerformed(evt);
            }
        });

        BThoat.setText("Thoát");
        BThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BGiaNhap))
                    .addComponent(CBUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BGoi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BThoat))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGiaNhap)
                    .addComponent(BThoat))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThoatActionPerformed
        try {
            // Create an output stream to send the disconnect message to the server
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(clientSocket.getOutputStream());
            objectOutputStream.writeObject(new DisconnectMessage(InetAddress.getLocalHost())); // Send a specific disconnection message object
            // Close the client socket
            userListUpdater.stop();
            clientSocket.close();
            BGiaNhap.setVisible(true);
            BThoat.setVisible(false);
            // Perform any other necessary cleanup or UI updates
        } catch (IOException ex) {
            ex.printStackTrace();
            // Handle any exceptions or display an error message to the user
        }
    }//GEN-LAST:event_BThoatActionPerformed

    private void BGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGiaNhapActionPerformed
        String userName = txtTenTaiKhoan.getText();
        
        try {
            clientSocket = new Socket("172.26.4.72", 5000);  // Initialize the class-level clientSocket
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(clientSocket.getOutputStream());
            objectOutputStream.writeObject(new User(userName, InetAddress.getLocalHost(), 6869));  // Send user information
            ObjectInputStream objectInputStream = new ObjectInputStream(clientSocket.getInputStream());
            List<User> userList = (List<User>) objectInputStream.readObject();  // Receive the updated user list
            userListUpdater = new UserListUpdater(clientSocket, userList, ListUser, CBUser);
            Thread updaterThread = new Thread(userListUpdater);
            updaterThread.start();
            BGiaNhap.setVisible(false);
            BThoat.setVisible(true);
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
            // Handle any exceptions or display an error message to the user
        }
    }//GEN-LAST:event_BGiaNhapActionPerformed

    private void BGoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGoiActionPerformed
        List<User> userList = userListUpdater.getUserList();
        String selectedUsername = (String) CBUser.getSelectedItem();
        String selectedUserIP = "";
        if (selectedUsername != null) {
            for (User user : userList) {
                if (user.Name.equals(selectedUsername)) {
                    InetAddress userIP = user.UserIP;
                    selectedUserIP = userIP.getHostAddress();
                    break;
                }
            }
            VideoCall calling = new VideoCall(selectedUserIP);
            calling.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error Can't Get username");
        }
        

    }//GEN-LAST:event_BGoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGiaNhap;
    private javax.swing.JButton BGoi;
    private javax.swing.JButton BThoat;
    private javax.swing.JComboBox<String> CBUser;
    private javax.swing.JList<String> ListUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
